import XCTest
@testable import ClippyCore

final class HistoryStoreTests: XCTestCase {

    private var directory: URL!

    override func setUpWithError() throws {
        directory = URL(fileURLWithPath: NSTemporaryDirectory())
            .appendingPathComponent("clippy-tests-\(UUID().uuidString)")
    }

    override func tearDownWithError() throws {
        try? FileManager.default.removeItem(at: directory)
    }

    private func makeStore() throws -> HistoryStore {
        try HistoryStore(directory: directory)
    }

    // MARK: - Round trip

    func testTextItemSurvivesAReopen() throws {
        let item = ClipItem(payload: .text("npm install"), sourceBundleID: "com.apple.Safari")
        try makeStore().upsert(item)

        let loaded = try makeStore().load()
        XCTAssertEqual(loaded.count, 1)
        XCTAssertEqual(loaded[0].id, item.id)
        XCTAssertEqual(loaded[0].payload, .text("npm install"))
        XCTAssertEqual(loaded[0].sourceBundleID, "com.apple.Safari")
    }

    func testImageRoundTripsThroughBlobStorage() throws {
        let data = Data((0..<512).map { UInt8($0 % 251) })
        let item = ClipItem(payload: .image(data: data, uti: "public.png"))
        try makeStore().upsert(item)

        let loaded = try makeStore().load()
        XCTAssertEqual(loaded.count, 1)
        XCTAssertEqual(loaded[0].payload, .image(data: data, uti: "public.png"))
    }

    func testRichTextRoundTripsWithItsFallback() throws {
        let rtf = Data([0x7B, 0x5C, 0x72, 0x74, 0x66])
        try makeStore().upsert(ClipItem(payload: .richText(rtf: rtf, plainFallback: "bold")))

        let loaded = try makeStore().load()
        XCTAssertEqual(loaded[0].payload, .richText(rtf: rtf, plainFallback: "bold"))
    }

    func testFilesRoundTrip() throws {
        let urls = [URL(fileURLWithPath: "/tmp/a.txt"), URL(fileURLWithPath: "/tmp/b.txt")]
        try makeStore().upsert(ClipItem(payload: .files(urls)))

        let loaded = try makeStore().load()
        XCTAssertEqual(loaded[0].payload, .files(urls))
    }

    func testMarkersSurvive() throws {
        try makeStore().upsert(ClipItem(payload: .text("x"), markers: [.autoGenerated]))
        XCTAssertEqual(try makeStore().load()[0].markers, [.autoGenerated])
    }

    // MARK: - Ordering and updates

    func testLoadIsNewestUseFirst() throws {
        let store = try makeStore()
        let now = Date()
        try store.upsert(ClipItem(capturedAt: now.addingTimeInterval(-100), payload: .text("old")))
        try store.upsert(ClipItem(capturedAt: now, payload: .text("new")))

        XCTAssertEqual(try store.load().map { $0.payload.plainText }, ["new", "old"])
    }

    func testTouchMovesAnItemToTheTop() throws {
        let store = try makeStore()
        let now = Date()
        let old = ClipItem(capturedAt: now.addingTimeInterval(-100), payload: .text("old"))
        try store.upsert(old)
        try store.upsert(ClipItem(capturedAt: now, payload: .text("new")))

        try store.touch(id: old.id, at: now.addingTimeInterval(10))
        XCTAssertEqual(try store.load().first?.payload.plainText, "old")
    }

    func testDeleteRemovesTheRow() throws {
        let store = try makeStore()
        let item = ClipItem(payload: .text("gone"))
        try store.upsert(item)
        try store.delete(id: item.id)
        XCTAssertTrue(try store.load().isEmpty)
    }

    func testUpsertOfSameIDReplacesRatherThanDuplicating() throws {
        let store = try makeStore()
        let id = UUID()
        try store.upsert(ClipItem(id: id, payload: .text("v1")))
        try store.upsert(ClipItem(id: id, payload: .text("v2")))

        let loaded = try store.load()
        XCTAssertEqual(loaded.count, 1)
        XCTAssertEqual(loaded[0].payload.plainText, "v2")
    }

    // MARK: - Blobs

    /// Content addressing: the same screenshot copied twice is one file.
    func testIdenticalBlobsAreStoredOnce() throws {
        let store = try makeStore()
        let data = Data(repeating: 0xAB, count: 1024)
        try store.upsert(ClipItem(payload: .image(data: data, uti: "public.png")))
        try store.upsert(ClipItem(payload: .image(data: data, uti: "public.png")))

        let blobs = try FileManager.default.contentsOfDirectory(
            at: directory.appendingPathComponent("blobs"), includingPropertiesForKeys: nil
        )
        XCTAssertEqual(blobs.count, 1)
    }

    func testEvictionDropsOldestItemsPastTheCount() throws {
        let store = try makeStore()
        let now = Date()
        for i in 0..<10 {
            try store.upsert(ClipItem(
                capturedAt: now.addingTimeInterval(Double(i)),
                payload: .text("item \(i)")
            ))
        }

        try store.evict(maxItems: 4, maxBlobBytes: HistoryLimits.maxBlobBytes)

        let loaded = try store.load()
        XCTAssertEqual(loaded.count, 4)
        XCTAssertEqual(loaded.first?.payload.plainText, "item 9")
    }

    /// A blob no row references any more is a file leak; eviction has to collect
    /// it, but must not touch one that is still referenced.
    func testEvictionCollectsOrphanedBlobsOnly() throws {
        let store = try makeStore()
        let now = Date()
        let keep = ClipItem(
            capturedAt: now.addingTimeInterval(10),
            payload: .image(data: Data(repeating: 0x01, count: 64), uti: "public.png")
        )
        let drop = ClipItem(
            capturedAt: now,
            payload: .image(data: Data(repeating: 0x02, count: 64), uti: "public.png")
        )
        try store.upsert(drop)
        try store.upsert(keep)

        try store.evict(maxItems: 1, maxBlobBytes: HistoryLimits.maxBlobBytes)

        let blobs = try FileManager.default.contentsOfDirectory(
            at: directory.appendingPathComponent("blobs"), includingPropertiesForKeys: nil
        )
        XCTAssertEqual(blobs.count, 1, "the evicted item's blob should be collected")
        XCTAssertEqual(try store.load().first?.id, keep.id)
    }

    func testBlobBudgetEvictsOldestFirst() throws {
        let store = try makeStore()
        let now = Date()
        let items = (0..<4).map { i in
            ClipItem(
                capturedAt: now.addingTimeInterval(Double(i)),
                payload: .image(data: Data(repeating: UInt8(i), count: 1000), uti: "public.png")
            )
        }
        for item in items { try store.upsert(item) }

        // Budget for two of the four 1000-byte blobs.
        try store.evict(maxItems: HistoryLimits.maxItems, maxBlobBytes: 2000)

        let loaded = try store.load()
        XCTAssertEqual(loaded.count, 2)
        XCTAssertEqual(Set(loaded.map(\.id)), Set([items[3].id, items[2].id]),
                       "the two most recently used blobs should survive")
    }

    // MARK: - Privacy

    /// The store is only ever handed persistable items — `History` filters first
    /// — but this pins the end-to-end guarantee that matters.
    func testConcealedItemsNeverReachDisk() throws {
        let store = try makeStore()
        let history = History(store: store)
        history.record(ClipItem(payload: .text("hunter2"), markers: [.concealed]))

        XCTAssertEqual(history.items.count, 1, "still usable in memory")
        XCTAssertTrue(try store.load().isEmpty, "but nothing on disk")

        let db = try String(contentsOf: directory.appendingPathComponent("history.db"),
                            encoding: .isoLatin1)
        XCTAssertFalse(db.contains("hunter2"), "no plaintext credential anywhere in the file")
    }

    func testOrdinaryItemsDoReachDiskThroughHistory() throws {
        let store = try makeStore()
        let history = History(store: store)
        history.record(ClipItem(payload: .text("ordinary")))

        XCTAssertEqual(try store.load().count, 1)
    }

    // MARK: - Forever history

    /// The default limits keep text forever; only the blob budget bites.
    func testDefaultEvictionKeepsEveryTextItem() throws {
        let store = try makeStore()
        let now = Date()
        for i in 0..<2_000 {
            try store.upsert(ClipItem(
                capturedAt: now.addingTimeInterval(Double(i)),
                payload: .text("item \(i)")
            ))
        }

        try store.evict()

        XCTAssertEqual(try store.load().count, 2_000)
        XCTAssertNil(HistoryLimits.maxItems)
    }

    /// Images are still capped, because they are the only payload big enough to
    /// matter.
    func testImagesAreStillEvictedUnderTheBlobBudget() throws {
        let store = try makeStore()
        let now = Date()
        for i in 0..<4 {
            try store.upsert(ClipItem(
                capturedAt: now.addingTimeInterval(Double(i)),
                payload: .image(data: Data(repeating: UInt8(i), count: 1000), uti: "public.png")
            ))
        }
        try store.upsert(ClipItem(capturedAt: now, payload: .text("text is never evicted")))

        try store.evict(maxBlobBytes: 2000)

        let loaded = try store.load()
        XCTAssertEqual(loaded.filter { if case .image = $0.payload { return true } else { return false } }.count, 2)
        XCTAssertEqual(loaded.filter { $0.payload.plainText == "text is never evicted" }.count, 1)
    }

    func testEvictionReportsWhatItRemoved() throws {
        let store = try makeStore()
        let now = Date()
        let old = ClipItem(capturedAt: now, payload: .image(
            data: Data(repeating: 0x01, count: 1000), uti: "public.png"))
        let new = ClipItem(capturedAt: now.addingTimeInterval(10), payload: .image(
            data: Data(repeating: 0x02, count: 1000), uti: "public.png"))
        try store.upsert(old)
        try store.upsert(new)

        let removed = try store.evict(maxBlobBytes: 1000)
        XCTAssertEqual(removed, [old.id])
    }

    /// An evicted image must disappear from the in-memory list too, or the panel
    /// would keep offering a clip whose data is gone until the next launch.
    func testHistoryDropsEvictedItemsFromMemory() throws {
        let store = try makeStore()
        let history = History(store: store, maxBlobBytes: 1500)

        history.record(ClipItem(payload: .image(
            data: Data(repeating: 0x01, count: 1000), uti: "public.png")))
        history.record(ClipItem(payload: .image(
            data: Data(repeating: 0x02, count: 1000), uti: "public.png")))

        // 2000 bytes against a 1500-byte budget: the older image has to go.
        XCTAssertEqual(history.items.count, 1)
        XCTAssertEqual(try store.load().count, 1)
        XCTAssertEqual(history.items.first?.payload,
                       .image(data: Data(repeating: 0x02, count: 1000), uti: "public.png"))
    }

    func testHistoryLoadsPersistedItemsOnLaunch() throws {
        let first = History(store: try makeStore())
        first.record(ClipItem(payload: .text("survives restart")))

        let second = History(store: try makeStore())
        second.loadFromStore()
        XCTAssertEqual(second.items.first?.payload.plainText, "survives restart")
    }
}
