import Foundation

/// Pasteboard marker types from the nspasteboard.org convention.
///
/// These are advisory UTIs that a copying application adds to the pasteboard to
/// tell clipboard managers how to treat the content. Honouring them is not
/// optional in any tool that persists history: password managers rely on
/// `concealed` to keep credentials out of your database.
///
/// Reference: https://nspasteboard.org
public enum MarkerType: String, CaseIterable, Sendable {

    /// Content is confidential. Must not be written to disk in plaintext, and
    /// should be visually obfuscated if displayed.
    case concealed = "org.nspasteboard.ConcealedType"

    /// Content is on the pasteboard only momentarily — the source intends to
    /// restore or replace it within seconds. Should not be recorded at all.
    case transient = "org.nspasteboard.TransientType"

    /// Content was generated by an application; the user never performed a copy
    /// and may be surprised to find it in their history.
    case autoGenerated = "org.nspasteboard.AutoGeneratedType"

    /// Content was placed by a clipboard manager restoring a previous item.
    /// Recording it would create duplicate entries in a feedback loop.
    case restored = "org.nspasteboard.RestoredType"
}

/// What a clipboard manager should do with an item, given its markers.
public enum RetentionPolicy: Equatable, Sendable {

    /// Persist to disk as normal.
    case persist

    /// Keep in memory only, redact in the UI, evict after `ttl`. Never write to
    /// disk. This is what `concealed` earns: the item stays usable for the
    /// "paste the password twice" case without a credential ever landing in the
    /// database.
    case memoryOnlyRedacted(ttl: TimeInterval)

    /// Do not record at all.
    case drop

    public static let concealedTTL: TimeInterval = 300
}

public extension RetentionPolicy {

    /// Decide retention from the marker types present on a pasteboard item.
    ///
    /// Order matters. `transient` and `restored` are dropped outright because
    /// recording them is either useless or actively harmful (feedback loops).
    /// `concealed` is downgraded rather than dropped. `autoGenerated` is kept
    /// but is a reasonable thing to let users filter out later.
    static func forMarkers(_ markers: Set<MarkerType>) -> RetentionPolicy {
        if markers.contains(.transient) || markers.contains(.restored) {
            return .drop
        }
        if markers.contains(.concealed) {
            return .memoryOnlyRedacted(ttl: concealedTTL)
        }
        return .persist
    }

    var isPersistable: Bool {
        self == .persist
    }

    var shouldRedact: Bool {
        if case .memoryOnlyRedacted = self { return true }
        return false
    }
}
